apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: test-wasm-plugin
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: http-gateway-netbird
  url: oci://ghcr.io/konstfish/oauth-redirect-wasm:0.1.0
  imagePullPolicy: Always
  phase: AUTHN
  pluginConfig:
    redirect_url: https://sso.barracuda.net.konst.fish/login
    redirect_param: rd
    add_redirect_param: true
    redirect_hosts:
      - localhost:10000